-- DNDApp schema (version 5: character sheets).
--
-- Kinds of tables:
--   SOURCE  - mirrors of what's in the archive folder (campaigns, accounts,
--             sessions, speakers, glossary, player notes, corrections,
--             character sheets).
--             Never wiped by rebuild.
--   DERIVED - everything the pipeline and the archivist generate. Wiped and
--             regenerated by rebuild. See wipeDerived() in db/index.js.
--   OPERATIONAL - jobs, usage and Q&A logs.

PRAGMA foreign_keys = ON;

-- ---------- SOURCE ----------

CREATE TABLE IF NOT EXISTS campaigns (
  id          INTEGER PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- People log in with name + password. The server admin sets passwords.
CREATE TABLE IF NOT EXISTS users (
  id             INTEGER PRIMARY KEY,
  name           TEXT NOT NULL UNIQUE COLLATE NOCASE,
  password_hash  TEXT,            -- scrypt; NULL = can't log in until the admin sets one
  must_change_password INTEGER NOT NULL DEFAULT 0,  -- set by the admin; cleared when they choose a new one
  is_admin       INTEGER NOT NULL DEFAULT 0,
  revoked_at     TEXT,
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS memberships (
  campaign_id     INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role            TEXT NOT NULL CHECK (role IN ('dm', 'player')),
  character_name  TEXT,
  PRIMARY KEY (campaign_id, user_id)
);

-- Maps a name as it appears in the transcript (Discord display name) to who it is.
CREATE TABLE IF NOT EXISTS speakers (
  campaign_id   INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  speaker       TEXT NOT NULL,
  display_name  TEXT NOT NULL,   -- e.g. "Thorin (Sam)" or "DM"
  user_id       INTEGER,         -- the account this speaker is; used for attendance and privacy
  PRIMARY KEY (campaign_id, speaker)
);

-- Correct spellings of names/terms, and the ways transcription gets them wrong.
CREATE TABLE IF NOT EXISTS glossary (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  term         TEXT NOT NULL,
  variants     TEXT NOT NULL DEFAULT '[]',  -- JSON array of misspellings
  note         TEXT,
  UNIQUE (campaign_id, term)
);

CREATE TABLE IF NOT EXISTS sessions (
  id               INTEGER PRIMARY KEY,
  campaign_id      INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  number           INTEGER NOT NULL,
  title            TEXT,
  played_on        TEXT NOT NULL,   -- YYYY-MM-DD; links the session to player notes from that date
  checksum         TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'archived',  -- archived | queued | processing | ready | failed
  error            TEXT,
  pipeline_version INTEGER,
  processed_at     TEXT,            -- ISO; when the archivist last finished it (schema v11)
  created_at       TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (campaign_id, number)
);

-- Notes players take during a session. Private to the author. The author can
-- edit or delete them; the archive keeps every version (schema v11).
CREATE TABLE IF NOT EXISTS player_notes (
  id            TEXT PRIMARY KEY,   -- random id, same as in the archive
  campaign_id   INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id       INTEGER NOT NULL,
  session_date  TEXT NOT NULL,      -- YYYY-MM-DD; matched to sessions.played_on
  written_at    TEXT NOT NULL,      -- ISO timestamp
  text          TEXT NOT NULL,
  edited_at     TEXT,               -- last edit, if any
  deleted_at    TEXT                -- deleted by the author: hidden everywhere
);
CREATE INDEX IF NOT EXISTS player_notes_lookup ON player_notes(campaign_id, session_date);

-- DM corrections in plain words. Applied by the archivist; reapplied on rebuild.
CREATE TABLE IF NOT EXISTS corrections (
  id             INTEGER PRIMARY KEY,
  campaign_id    INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  text           TEXT NOT NULL,
  after_session  INTEGER NOT NULL,  -- apply once this session has been processed
  created_by     INTEGER,
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Each player's character sheet in a campaign. Private to that player. The
-- archive keeps every change (character-sheets/<user id>.jsonl).
CREATE TABLE IF NOT EXISTS character_sheets (
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  data         TEXT NOT NULL,     -- JSON; see packages/shared/src/sheet.js
  version      INTEGER NOT NULL,  -- goes up by one with each save
  updated_at   TEXT NOT NULL,
  PRIMARY KEY (campaign_id, user_id)
);

-- Maps the DM imported (image + grid, scale, tokens), one JSON document each.
-- Seen by players only once shown. The archive keeps the image as uploaded and
-- every change (maps/<id>/changes.jsonl). Schema v7.
CREATE TABLE IF NOT EXISTS maps (
  id           TEXT PRIMARY KEY,  -- random, also the archive folder name
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  data         TEXT NOT NULL,     -- JSON; see packages/shared/src/map.js
  version      INTEGER NOT NULL,  -- goes up by one with each change
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS maps_campaign ON maps(campaign_id);

-- Each person's private pins on a map: only they ever see them, not even the
-- DM. Archived as maps/<id>/pins/<user id>.jsonl (the whole list per line). Schema v8.
CREATE TABLE IF NOT EXISTS map_pins (
  map_id      TEXT NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL,
  data        TEXT NOT NULL,      -- JSON list; see normalizePins in packages/shared/src/map.js
  updated_at  TEXT NOT NULL,
  PRIMARY KEY (map_id, user_id)
);

-- Where each player has seen on a map with line of sight on (shown to them dimmed).
-- Not archived: a convenience, forgotten if the database is rebuilt. See maps/sight.js.
CREATE TABLE IF NOT EXISTS map_explored (
  map_id      TEXT NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL,
  data        TEXT NOT NULL,      -- base64 bitset, one bit per cell, row by row
  cols        INTEGER NOT NULL,
  rows        INTEGER NOT NULL,
  updated_at  TEXT NOT NULL,
  PRIMARY KEY (map_id, user_id)
);

-- A player's token and full picture of their character (files in the archive under characters/<user id>/).
CREATE TABLE IF NOT EXISTS character_pictures (
  campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL REFERENCES users(id),
  data        TEXT NOT NULL,      -- JSON { token, picture }; see normalizePictures in src/characters/pictures.js
  updated_at  TEXT NOT NULL,
  PRIMARY KEY (campaign_id, user_id)
);

-- Handouts the DM gives players (a picture and/or text), to everyone or chosen
-- players. Archived as handouts/<id>/changes.jsonl (the whole handout each
-- time) plus the picture as uploaded. Schema v11.
CREATE TABLE IF NOT EXISTS handouts (
  id           TEXT PRIMARY KEY,  -- random, also the archive folder name
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  data         TEXT NOT NULL,     -- JSON; see normalizeHandout in src/handouts.js
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS handouts_campaign ON handouts(campaign_id);

-- The DM's saved enemies and NPCs, placed on maps as tokens. Archived as
-- creatures/<id>/changes.jsonl (the whole creature each time) plus its
-- picture as uploaded. Schema v12.
CREATE TABLE IF NOT EXISTS creatures (
  id           TEXT PRIMARY KEY,  -- random, also the archive folder name
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  data         TEXT NOT NULL,     -- JSON; see normalizeCreature in src/creatures.js
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS creatures_campaign ON creatures(campaign_id);

-- ---------- DERIVED ----------

-- How far the archivist has read sheet changes and note edits (see kb/updates.js). Schema v11.
CREATE TABLE IF NOT EXISTS archivist_marks (
  campaign_id    INTEGER PRIMARY KEY REFERENCES campaigns(id) ON DELETE CASCADE,
  updates_until  TEXT NOT NULL      -- ISO timestamp
);

-- Who was at each session (from the speaker map, player notes, and the archivist).
CREATE TABLE IF NOT EXISTS attendance (
  session_id  INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL,
  PRIMARY KEY (session_id, user_id)
);

-- The archivist's knowledge base. Organised however the AI sees fit.
CREATE TABLE IF NOT EXISTS kb_records (
  id             INTEGER PRIMARY KEY,
  campaign_id    INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  kind           TEXT NOT NULL,          -- free-form, chosen by the AI ("_guide" is reserved)
  title          TEXT NOT NULL,
  body           TEXT NOT NULL DEFAULT '',
  data           TEXT NOT NULL DEFAULT '{}',   -- JSON, free-form
  status         TEXT NOT NULL DEFAULT '',
  tags           TEXT NOT NULL DEFAULT '[]',
  known_by       TEXT,                   -- NULL = every member; else JSON array of user ids
  pinned         INTEGER NOT NULL DEFAULT 0,   -- always loaded into Q&A (for those who may see it)
  sources        TEXT NOT NULL DEFAULT '[]',
  first_session  INTEGER,
  last_session   INTEGER,
  created_at     TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at     TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS kb_records_lookup ON kb_records(campaign_id, kind, status);

-- Every change the archivist makes, with its reason.
CREATE TABLE IF NOT EXISTS kb_journal (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  run          TEXT NOT NULL,     -- e.g. "session 12" or "correction 4"
  op           TEXT NOT NULL,     -- create | update | delete | guide
  record_id    INTEGER,
  before       TEXT,
  after        TEXT,
  reason       TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Questions the archivist wants the DM to answer (conflicts, uncertainties).
CREATE TABLE IF NOT EXISTS dm_questions (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  run          TEXT NOT NULL,
  question     TEXT NOT NULL,
  context      TEXT NOT NULL DEFAULT '',
  status       TEXT NOT NULL DEFAULT 'open',   -- open | answered | dismissed
  answer       TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Unified search index: transcript chunks, knowledge-base records, player notes.
CREATE TABLE IF NOT EXISTS docs (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  kind         TEXT NOT NULL,     -- chunk | kb | note
  ref_id       TEXT,              -- kb record id / player note id
  session_num  INTEGER,
  start_sec    INTEGER,
  end_sec      INTEGER,
  title        TEXT NOT NULL,
  text         TEXT NOT NULL,
  visible_to   TEXT,              -- NULL = every member; else JSON array of user ids
  embedding    BLOB,
  embed_model  TEXT
);
CREATE INDEX IF NOT EXISTS docs_lookup ON docs(campaign_id, kind, session_num);
CREATE INDEX IF NOT EXISTS docs_ref ON docs(campaign_id, kind, ref_id);

CREATE VIRTUAL TABLE IF NOT EXISTS docs_fts USING fts5(
  title, text, content='docs', content_rowid='id', tokenize='porter unicode61'
);

CREATE TRIGGER IF NOT EXISTS docs_ai AFTER INSERT ON docs BEGIN
  INSERT INTO docs_fts(rowid, title, text) VALUES (new.id, new.title, new.text);
END;
CREATE TRIGGER IF NOT EXISTS docs_ad AFTER DELETE ON docs BEGIN
  INSERT INTO docs_fts(docs_fts, rowid, title, text) VALUES ('delete', old.id, old.title, old.text);
END;
CREATE TRIGGER IF NOT EXISTS docs_au AFTER UPDATE OF title, text ON docs BEGIN
  INSERT INTO docs_fts(docs_fts, rowid, title, text) VALUES ('delete', old.id, old.title, old.text);
  INSERT INTO docs_fts(rowid, title, text) VALUES (new.id, new.title, new.text);
END;

-- ---------- OPERATIONAL ----------

-- Logged-in browsers. Not archived: after losing the database, people log in again.
CREATE TABLE IF NOT EXISTS logins (
  token_hash    TEXT PRIMARY KEY,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  last_used_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Dice rolls, shared live with the party, the DM, or kept to yourself. Schema v11.
CREATE TABLE IF NOT EXISTS rolls (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id      INTEGER NOT NULL,
  visibility   TEXT NOT NULL,     -- party | dm | self
  label        TEXT NOT NULL DEFAULT '',
  result       TEXT NOT NULL,     -- JSON, as rollDice returns it
  rolled_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS rolls_campaign ON rolls(campaign_id, id);

CREATE TABLE IF NOT EXISTS jobs (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  type         TEXT NOT NULL,     -- ingest | correct | updates | rebuild
  params       TEXT NOT NULL DEFAULT '{}',
  status       TEXT NOT NULL DEFAULT 'queued',  -- queued | running | done | failed
  progress     REAL NOT NULL DEFAULT 0,
  message      TEXT,
  error        TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  finished_at  TEXT
);

-- Every LLM call, for cost tracking and spending caps.
CREATE TABLE IF NOT EXISTS llm_usage (
  id                   INTEGER PRIMARY KEY,
  provider             TEXT NOT NULL DEFAULT 'api',  -- 'api' (billed) or 'claude-code' (subscription; cost is an estimate)
  campaign_id          INTEGER,
  user_id              INTEGER,
  purpose              TEXT NOT NULL,
  model                TEXT NOT NULL,
  input_tokens         INTEGER NOT NULL DEFAULT 0,
  output_tokens        INTEGER NOT NULL DEFAULT 0,
  cache_read_tokens    INTEGER NOT NULL DEFAULT 0,
  cache_write_tokens   INTEGER NOT NULL DEFAULT 0,
  cost_usd             REAL NOT NULL DEFAULT 0,
  duration_ms          INTEGER,
  created_at           TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS llm_usage_created ON llm_usage(provider, created_at);

CREATE TABLE IF NOT EXISTS conversations (
  id           INTEGER PRIMARY KEY,
  campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title        TEXT,
  pinned       INTEGER NOT NULL DEFAULT 0,
  -- Deleted by the player: hidden, and its questions and answers erased. The rows stay so the
  -- hourly question limit and usage figures still count them.
  deleted_at   TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS qa_log (
  id               INTEGER PRIMARY KEY,
  conversation_id  INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id          INTEGER NOT NULL,
  question         TEXT NOT NULL,
  answer           TEXT,
  evidence         TEXT NOT NULL DEFAULT '[]',  -- JSON: sources behind the answer's citations
  tool_calls       TEXT NOT NULL DEFAULT '[]',  -- JSON: how the answer was found
  cost_usd         REAL NOT NULL DEFAULT 0,
  duration_ms      INTEGER,   -- question received -> answer finished
  first_text_ms    INTEGER,   -- question received -> first answer text streamed
  status           TEXT NOT NULL DEFAULT 'ok',
  created_at       TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS qa_log_user ON qa_log(user_id, created_at);
